config/routes.rb
Rails.application.routes.draw do
	root  'forums#index'
	resources :posts, except: [:index]
	resources :topics, except: [:index]
	resources :forums

	resources :users
	resources :sessions,   only: [:new, :create, :destroy]

	match '/signup',  to: 'users#new',			  via: 'get'
	match '/signin',  to: 'sessions#new',         via: 'get'
	match '/signout', to: 'sessions#destroy',     via: 'delete'

	match '/help',    to: 'static_pages#help',    via: 'get'
	match '/about',   to: 'static_pages#about',   via: 'get'
	match '/contact', to: 'static_pages#contact', via: 'get'

	match '/topics', to: 'topics#index',	via: 'get'

	match "*path" => redirect("/"), via: 'get'

			end

app/models/forum.rb
class Forum < ActiveRecord::Base
	has_many :topics, :dependent => :destroy



	def most_recent_post
		topic = Topic.first(:order => 'last_post_at DESC', :conditions => ['forum_id = ?', self.id])
		return topic
	end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  #before_action :set_forum, only: [:show, :edit, :update, :destroy]
  before_filter :admin_required, :except => [:index, :show]

  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
    @forum = Forum.find(params[:id])
    @topics = @forum.topics.order("last_post_at desc").paginate(:page => params[:page])
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(forum_params)
      if @forum.save
        redirect_to @forum, :flash => {:notice => "Forum was successfully created."}
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:name, :description)
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= form_for(@forum), :html => {:class => "input_area"} do |f| %>
  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% @forum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forums/_forum.html.erb
<tr>
    <td>
      <h4><%= link_to h(forum.name), forum_path(forum.id) %></h4>
      <small>
        <%=h forum.description %><br />
        <%= forum.topics.count %> threads
      </small>
        <td class="right">
            <%= distance_of_time_in_words_to_now forum.updated_at %> ago
        </td>
    </td>
      
      <% if admin? %>
       <td><%= link_to "Edit", edit_forum_path(forum) %></td>
       <td><%= link_to "Destroy", forum, :confirm => 'Are you sure?', :method => :delete %></td>
      <% end %>
</tr>

app/views/forums/edit.html.erb
<h1>Editing forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<h1>Forums</h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th width="92%">Forum</th>
    <th width="10%">Last Activity</th>
  </tr>

  <%= render @forums %>

</table>

<% if admin? %>
  <p><%= link_to "New Forum", new_forum_path %></p>
<% end %>

app/views/forums/new.html.erb
<h1>New forum</h1>

<%= render 'form' %>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<h1><%= @forum.name  %></h1>
<p id="notice"><%= notice %></p>
<table>
	<tr>
		<th width="70%">Thread Title</th>
		<th width="10%">Replies</th>
		<th width="10%">Last Post</th>
	</tr>

	<%= will_paginate @topics %>
	<%= render @topics %>
	<%= will_paginate @topics %>

</table>

	<p class="new_thread"><% if signed_in? %><%= link_to "New Thread", "/topics/new?forum=#{@forum.id}" %><% end %></p>