config/routes.rb
Rails.application.routes.draw do
	root  'forums#index'
	resources :posts, except: [:index]
	resources :topics, except: [:index]
	resources :forums

	resources :users
	resources :sessions,   only: [:new, :create, :destroy]

	match '/signup',  to: 'users#new',			  via: 'get'
	match '/signin',  to: 'sessions#new',         via: 'get'
	match '/signout', to: 'sessions#destroy',     via: 'delete'

	match '/help',    to: 'static_pages#help',    via: 'get'
	match '/about',   to: 'static_pages#about',   via: 'get'
	match '/contact', to: 'static_pages#contact', via: 'get'

	match '/topics', to: 'topics#index',	via: 'get'

	match "*path" => redirect("/"), via: 'get'

			end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :forum
	belongs_to :user
	has_many :posts, :dependent => :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	before_filter :signed_in_user, :except => [:index, :show]
	before_filter :admin_required, :only => :destroy

	def index
		@topics = Topic.all
	end

	def show
		@topic = Topic.find(params[:id])
		@posts = @topic.posts.order("created_at desc").paginate(:page => params[:page])
	end

	def new
		@topic = Topic.new
	end 

	def create
		@topic = Topic.new(:name => params[:topic][:name], :last_poster_id => current_user.id, :last_post_at => Time.now, :forum_id => params[:topic][:forum_id], :user_id => current_user.id)
		if @topic.save
				flash[:notice] = "Successfully created topic."
				redirect_to new_post_url(topic: @topic.id)
		else
			render :action => 'new'
		end
	end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for @topic, :html => {:class => 'input_area'} do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<% if params[:forum] %>
<input type="hidden" id="topic_forum_id" name="topic[forum_id]" value="<%= params[:forum] %>" />
<% end %>
<p>
	<%= f.label :name %><br />
	<%= f.text_field :name %>


</p>
<p>

	
</p>
<p><%= f.submit "Create" %></p>
<% end %>

app/views/topics/_topic.html.erb
<tr>
	<td width="80%">
		<%= link_to h(topic.name), topic_path(topic.id) %>
	</td>

	<td>
		<%= topic.posts.count %>
	</td>

	<td class="right">
		<%= distance_of_time_in_words_to_now topic.last_post_at %> ago by 
		<%= link_to topic.user.name, "/users/#{topic.last_poster_id}" %>
	</td>

	<% if admin? %>
	<td>
		<%= link_to "Delete", topic, :confirm => 'Are you sure?', :method => :delete %>
	</td>
	<% end %>

</tr>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing threads</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last poster</th>
      <th>Last post at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.last_poster_id %></td>
        <td><%= topic.last_post_at %></td>

        <% if admin? %>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New thread</h1>

<%= render 'topics/form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<p id="notice"><%= notice %></p>

<%= will_paginate @posts %>

<%= render @posts %>

<p>
	<% if signed_in? %>
	<%= link_to "Reply", "#{new_post_path}?topic=#{@topic.id}" %> |
	<% end %>
	<% if admin? %><%= link_to "Destroy Thread", @topic, :confirm => 'Are you sure?', :method => :delete %> |<% end %>
	<%= link_to "View All Threads", forum_path(@topic.forum_id) %>
</p>