config/routes.rb
Rails.application.routes.draw do
	root  'forums#index'
	resources :posts, except: [:index]
	resources :topics, except: [:index]
	resources :forums

	resources :users
	resources :sessions,   only: [:new, :create, :destroy]

	match '/signup',  to: 'users#new',			  via: 'get'
	match '/signin',  to: 'sessions#new',         via: 'get'
	match '/signout', to: 'sessions#destroy',     via: 'delete'

	match '/help',    to: 'static_pages#help',    via: 'get'
	match '/about',   to: 'static_pages#about',   via: 'get'
	match '/contact', to: 'static_pages#contact', via: 'get'

	match '/topics', to: 'topics#index',	via: 'get'

	match "*path" => redirect("/"), via: 'get'

			end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :topic
	belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	before_filter :signed_in_user

	# GET /posts
	# GET /posts.json
	def index
		@posts = Post.paginate(:page => params[:page])
	end

	# GET /posts/1
	# GET /posts/1.json
	def show
	end

	# GET /posts/new
	def new
		@post = Post.new
	end

	# GET /posts/1/edit


	def create
		@post = Post.new(:content => params[:post][:content], :topic_id => params[:post][:topic_id], :user_id => current_user.id)
		if @post.save
			@topic = Topic.find(@post.topic_id)
			@topic.update_attributes(:last_poster_id => current_user.id, :last_post_at => Time.now)

			@forum = Forum.find(@topic.forum_id)
			@forum.update_attributes(:last_poster_id => current_user.id, :last_post_at => Time.now)
			flash[:notice] = "Successfully created post."
			redirect_to @topic
		else
			render :action => 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
		admin_or_owner_required(@post.user.id)
	end
	
	def update
		@post = Post.find(params[:id])
		admin_or_owner_required(@post.user.id)
		if @post.update_attributes(post_params)
			@topic = Topic.find(@post.topic_id)
			@topic.update_attributes(:last_poster_id => current_user.id, :last_post_at => Time.now)
			flash[:notice] = "Successfully updated post."
			redirect_to "/topics/#{@post.topic_id}"
		else
			render :action => 'edit'
		end
	end
	
	def destroy
		@post = Post.find(params[:id])
		admin_or_owner_required(@post.user.id)
		@post.destroy
		flash[:notice] = "Successfully destroyed post."
		redirect_to forums_url
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_post
		@post = Post.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def post_params
		params.require(:post).permit(:content)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, :html => {:class => "input_area"}  do |f| %>
<% if @post.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

	<ul>
		<% @post.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% if params[:topic] %><input type="hidden" id="topic_forum_id" name="post[topic_id]" value="<%= params[:topic] %>" /><% end %>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :content %><br>
	<%= f.text_area :content %>

	<input type="hidden" name="post[topic_id]" value=<%= params[:topic] %> />
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/posts/_post.html.erb
<div class="post" >
	<span class="left"><%= link_to post.user.name, user_url(post.user) %>:
		
		
		<br />
		<span class="content"><%= post.content %></span>
		
		<span class="right"><small>Posted at <%=post.created_at%></small></span>
		<br />
		
		<% if signed_in? %>
			<% if admin_or_owner?(post.user.id) %>
			<small>
				<%= link_to "Edit", edit_post_path(post) %>
				<%= link_to "Delete", post, :confirm => 'Are you sure?', :method => :delete %>
			</small>
			<% end %>
		<% end %>
	</span>
<br />
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= will_paginate %>
      <%= render @posts%>
    <%= will_paginate %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>